name: Deploy ToDo App (Local)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Restart container using docker-compose
        run: |
          docker compose -f /home/turko/course-work/docker-compose.yml down
          docker compose -f /home/turko/course-work/docker-compose.yml up -d
